<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs

// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import Header from './components/header.vue'
import Footer from './components/footer.vue'
</script>

<template>
  <Header />
  <main>
    <router-view />
  </main>

  <Footer />
</template>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="scss">
/*!
 *  Iconly icon font. Generated by Iconly: https://iconly.io/
 */

@font-face {
  font-display: auto;
  font-family: 'Iconly';
  font-style: normal;
  font-weight: 400;
  src: url('./assets/fonts/icons/iconly.eot?1662118872208');
  src: url('./assets/fonts/icons/iconly.eot?#iefix') format('embedded-opentype'), url('./assets/fonts/icons/iconly.woff2?1662118872208') format('woff2'),
    url('./assets/fonts/icons/iconly.woff?1662118872208') format('woff'), url('./assets/fonts/icons/iconly.ttf?1662118872208') format('truetype'),
    url('./assets/fonts/icons/iconly.svg?1662118872208#Iconly') format('svg');
}

[class='icon'],
[class^='icon-'],
[class*=' icon-'] {
  color: var(--scheme-v3);
  display: inline-block;
  font-family: 'Iconly' !important;
  font-weight: 400;
  font-style: normal;
  font-variant: normal;
  line-height: 1;
  text-rendering: auto;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
}

.icon-lock:before {
  content: '\e000';
}

.icon-wallet:before {
  content: '\e001';
}

.icon-swap:before {
  content: '\e002';
}

.icon-shield-done:before {
  content: '\e003';
}

.icon-password:before {
  content: '\e004';
}

.icon-call:before {
  content: '\e005';
}

.icon-buy:before {
  content: '\e006';
}

.icon-bag:before {
  content: '\e007';
}

.icon-filter-2:before {
  content: '\e008';
}

.icon-location:before {
  content: '\e009';
}

.icon-tick-square:before {
  content: '\e00a';
}

.icon-ticket-star:before {
  content: '\e00b';
}

.icon-solana:before {
  content: '\e00c';
}

.icon-bnb:before {
  content: '\e00d';
}

.icon-telegram:before {
  content: '\e00e';
}

.icon-twitter:before {
  content: '\e00f';
}

.icon-ethereum:before {
  content: '\e010';
}

.icon-instagram:before {
  content: '\e011';
}

.icon-chat:before {
  content: '\e012';
}

.icon-activity:before {
  content: '\e013';
}

.icon-arrow-down-circle:before {
  content: '\e014';
}

.icon-apple:before {
  content: '\e015';
}

.icon-google:before {
  content: '\e016';
}

.icon-edit:before {
  content: '\e017';
}

.icon-document:before {
  content: '\e018';
}

.icon-3-user:before {
  content: '\e019';
}

// initialize project fonts from @assets
@font-face {
  font-family: 'Renner*';
  src: local('./assets/fonts/renner-light'), url('./assets/fonts/renner-light.otf') format('opentype');
  font-weight: 300;
}

@font-face {
  font-family: 'Renner*';
  src: local('./assets/fonts/renner-book'), url('./assets/fonts/renner-book.otf') format('opentype');
  font-weight: 400;
}

@font-face {
  font-family: 'Renner*';
  src: local('./assets/fonts/renner-medium'), url('./assets/fonts/renner-medium.otf') format('opentype');
  font-weight: 500;
}

:root {
  // project color palete
  --scheme-v1: #151f32; // primary scheme
  --scheme-v2: #ffffff;
  --scheme-v3: #4e94d7;
  --scheme-v4: #f4f7fc;

  // project gradient palete
  --scheme-gradient: linear-gradient(to right, var(--scheme-v3), var(--scheme-v4));

  // project default template sizes
  --header-size: 25px;

  // project font-family
  --scheme-font: 'Renner*', 'Helvetica', sans-serif;
  --scheme-h: 46px;
  --scheme-m: 32px;
  --scheme-s: 18px;

  // project default template width
  --scheme-max-width: 1280px; // desktop
  --scheme-min-width: 320px; // 5 SE

  // project default template height
  --scheme-min-height: 568px; // 5 SE

  // project default template gap
  --scheme-gap: 40px;

  // project ex. header & footer height
  --scheme-offset: 100px;

  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -webkit-text-size-adjust: 100%;
}

@media only screen and (max-width: 928px) {
  :root {
    --scheme-h: 42px;
    --scheme-m: 26px;
  }
}

* {
  box-sizing: border-box;
}

body {
  background: var(--scheme-v2);
  color: var(--scheme-v1);

  font: 300 17px / 1.64 var(--scheme-font);

  margin: 0;
  position: relative;

  // user-select: none;
  ::selection {
    background: var(--scheme-v3);
  }
}

section {
  margin: 100px auto;
  max-width: var(--scheme-max-width);
  padding: 20px;

  @media only screen and (max-width: 928px) {
    text-align: center;
  }
}

h1,
h2,
h3,
h4,
h5 {
  font-weight: 300;
  margin: 0;
}

h1 {
  font: 300 var(--scheme-h) / 1.42 var(--scheme-font);
}

h2 {
  font: 300 var(--scheme-m) / 1.42 var(--scheme-font);

  margin: 0 0 40px;
}

h3 {
  font: 400 var(--scheme-s) / 1.42 var(--scheme-font);
}

a {
  color: inherit;
  text-decoration: none;
}

b {
  font-weight: 400;
}

p {
  margin: 0;
}

strong {
  font: inherit;
}

ul {
  margin: 0;
  padding: 0;

  li {
    list-style: none;
  }
}

picture,
figure {
  margin: 0;

  img {
    display: block;
    // object-fit: cover;
    width: 100%;

    @media only screen and (max-width: 928px) {
      margin: auto;
      max-width: 280px !important;
    }
  }
}

svg {
  fill: var(--scheme-v3);
  vertical-align: middle;
}

input,
button {
  background: none;
  border: none;
  box-shadow: none;

  font: var(--scheme-font);

  margin: 0;
  outline: none;
  padding: 0;
}

// set default button properties
button,
.button {
  background-color: var(--scheme-v3);
  border-radius: 50px;
  color: var(--scheme-v2);

  cursor: pointer;

  display: inline-block;

  font-size: var(--scheme-s);
  margin: 40px 0;
  padding: 16px 80px;
}
</style>
